#!/usr/bin/env python3
"""Build QE TextMate grammars. Parameter assignments are syntax based so
new QE variables and utility-specific namelists work without a stale list.
References: https://www.quantum-espresso.org/documentation/input-data-description/
"""
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DATA = json.loads((ROOT / 'qe-syntax-data.json').read_text())
CARDS = '|'.join(re.escape(name) for name in sorted(DATA['cards'], key=lambda n: (-len(n), n)))
NUMBER = r'(?<![\w.])[-+]?(?:\d+\.?\d*|\.\d+)(?:[eEdD][-+]?\d+)?(?![\w.])'
OUT_NUMBER = r'(?<![\w.])[-+]?(?:\d+\.\d*[eEdD][-+]?\d+|\d+\.\d+|\.\d+|\d+)(?:[eEdD][-+]?\d+)?(?![\w.])'
ELEMENT = (r'(?:A[cglmrstu]|B[aehikr]?|C[adeflmnorsu]?|D[bsy]|E[rsu]|F[elmr]?|G[ade]|'
           r'H[efgos]?|I[nr]?|Kr?|L[airuv]|M[cdgnot]|N[abdehiop]?|O[gs]?|P[abdmortu]?|'
           r'R[abefghnu]|S[bcegimnr]?|T[abcehilms]|U|V|W|Xe|Yb?|Z[nr])')
FILE_EXT = r'upf|wfc|in|inp|out|log|dat|xml|save|sav|xsf|cube|h5|hdf5|gnu|eig|xanes|nml|json|txt'


def rule(regex, scope):
    return {'match': regex, 'name': scope}


def captures(**scopes):
    return {key: {'name': value} for key, value in scopes.items()}


def input_grammar():
    return {
        'name': 'Quantum ESPRESSO Input', 'scopeName': 'source.qe',
        'comment': 'Generated by tools/build_qe_grammars.py; edit the builder.',
        'patterns': [{'include': '#' + name} for name in
                     ['comments', 'strings', 'namelist', 'assignment', 'cards', 'species', 'values', 'fallback']],
        'repository': {
            'comments': {'patterns': [
                {'begin': '!', 'end': '$', 'name': 'comment.line.exclamation.qe'},
                {'begin': r'^\s*#', 'end': '$', 'name': 'comment.line.number-sign.qe'},
            ]},
            'strings': {'patterns': [
                {'begin': quote, 'end': quote + '|$', 'name': 'string.quoted.' + kind + '.qe',
                 'applyEndPatternLast': True,
                 'patterns': [rule(quote + quote, 'constant.character.escape.qe')]}
                for quote, kind in [("'", 'single'), ('"', 'double')]
            ]},
            'namelist': {'patterns': [
                rule(r'(?i)^\s*(?:&end\b|/)|&end\b', 'punctuation.definition.namelist.end.qe keyword.other.namelist-end.qe'),
                {'match': r'^\s*(&)([A-Za-z_]\w*)', 'captures': captures(**{
                    '1': 'punctuation.definition.namelist.qe storage.type.namelist.marker.qe', '2': 'storage.type.namelist.qe'})},
            ]},
            'cards': {'patterns': [
                {'match': rf'(?i)^\s*({CARDS})\b(?![ \t]*(?:\([^()\r\n]*\)[ \t]*)?=)',
                 'captures': captures(**{'1': 'keyword.control.card.qe'})},
                rule(r'(?i)\b(?:alat|bohr|angstrom|crystal_sg|crystal_b|crystal_c|crystal|'
                     r'tpiba_b|tpiba_c|tpiba|automatic|gamma|atomic|ortho-atomic|norm-atomic|wf|pseudo)\b',
                     'support.constant.option.qe constant.language.option.qe'),
                rule(r'(?i)^\s*(?:U|J0|J|V|B|E2|E3|ALPHA)\b(?![ \t]*(?:\([^()\r\n]*\)[ \t]*)?=)',
                     'keyword.other.hubbard.qe'),
            ]},
            'assignment': {
                'match': r'(?i)\b([a-z_]\w*(?:%[a-z_]\w*)*)(\s*\([^\n()]*\))?(\s*)(=)',
                'captures': {
                    '1': {'name': 'keyword.other.variable.qe'},
                    '2': {'name': 'meta.array-index.qe', 'patterns': [{'include': '#values'}]},
                    '4': {'name': 'keyword.operator.assignment.qe keyword.other.operator.assignment.qe'},
                },
            },
            'species': {'patterns': [
                {'match': r'^\s*([A-Za-z][\w+-]*)(?=\s+[-+.\d])',
                 'captures': captures(**{'1': 'constant.language.species.qe'})},
                rule(r'(?i)(?<![\w])[^\s\x27"!,]+\.upf\b', 'string.unquoted.pseudopotential.qe'),
                rule(r'(?i)(?<![\w])\d+[spdfghij](?![\w])', 'constant.language.orbital.qe'),
            ]},
            'values': {'patterns': [
                rule(r'(?i)\.(?:true|false|t|f)\.', 'constant.language.boolean.qe'),
                rule(NUMBER, 'constant.numeric.qe'),
                rule(r'=', 'keyword.operator.assignment.qe keyword.other.operator.assignment.qe'),
                rule(r'(?i)\.(?:and|or|not|eqv|neqv|eq|ne|lt|le|gt|ge)\.|[*/:+<>-]',
                     'keyword.operator.qe keyword.other.operator.qe'),
                rule(r',', 'punctuation.separator.qe keyword.other.separator.qe'),
                rule(r'[(){}\[\]]', 'punctuation.section.qe keyword.other.group.qe'),
            ]},
            'fallback': {'patterns': [
                rule(r'[A-Za-z_][\w.+%-]*', 'support.type.property-name.bare.qe'),
                rule(r'\S', 'punctuation.other.qe keyword.other.symbol.qe'),
            ]},
        },
    }


def output_grammar():
    name = 'support.type.property-name.qe-output'
    note = 'comment.line.note.qe-output'
    operator = 'keyword.operator.qe-output keyword.other.operator.qe-output'
    heading = 'markup.heading.section.qe-output'
    inline = [{'include': '#' + key} for key in
              ['url', 'path', 'filename', 'quoted-string', 'checksum', 'time',
               'assignment', 'species', 'orbitals', 'prose-variable', 'units', 'values', 'symbols']]
    # Capture patterns retain the surrounding heading/property scope; body
    # text has an explicit secondary colour. Avoid consuming whole lines with
    # a generic fallback, which would hide later numbers, paths or variables.
    return {
        'name': 'Quantum ESPRESSO Output', 'scopeName': 'source.qe-output',
        'comment': 'Generated by tools/build_qe_grammars.py; edit the builder.',
        'patterns': [{'include': '#' + name} for name in
                     ['status', 'banner', 'number-row', 'sections', 'table',
                      'energy', 'labels', 'input', 'text']],
        'repository': {
            'status': {'patterns': [
                # Error delimiters frame routine diagnostics in QE outputs.
                {'begin': r'^\s*%{5,}.*$', 'end': r'^\s*%{5,}.*$',
                 'name': 'invalid.illegal.error.qe-output'},
                rule(r'(?i)^.*(?:Error in routine|convergence NOT achieved|Maximum CPU time exceeded|'
                     r'\b(?:error|fatal)\b).*$', 'invalid.illegal.diagnostic.qe-output'),
                rule(r'(?i)^.*(?:\bwarning\b|floating-point exceptions).*$', 'markup.deleted.warning.qe-output'),
                rule(r'(?i)^.*(?:JOB DONE\.|convergence has been achieved|End of self-consistent calculation).*$',
                     'markup.inserted.success.qe-output'),
            ]},
            'banner': {'match': r'(?i)^\s*(Program\s+\S+)\s+(v\.[\d.]+)(.*)$',
                       'captures': captures(**{'1': 'markup.heading.program.qe-output',
                                               '2': 'constant.numeric.version.qe-output'}) | {
                           '3': {'patterns': [{'include': '#text'}]}},
            },
            'number-row': {
                'match': r'^\s*[-+\d.][\d.eEdD+\-\s]*\s*$',
                'name': 'constant.numeric.row.qe-output',
            },
            'sections': {'patterns': [
                rule(r'^\s*[=+|]?[-=*_]{5,}[=+|]?\s*$', 'comment.line.separator.qe-output'),
                {'match': r'(?i)^\s*(Self-consistent Calculation|Band Structure Calculation|'
                     r'iteration #\s*\d+.*|Forces acting on atoms.*|total\s+stress.*|'
                     r'Begin final coordinates|End final coordinates|(?:crystal|reciprocal|Cartesian) axes:?.*|'
                     r'Parallelization info|Using Slab Decomposition|(?:General|Parallel|PAW) routines|'
                     r'(?:Reading|Getting|Starting|Attributing|Energy zero) [A-Za-z][^=:]*|'
                     r'\S.*bands \(ev\):.*)\s*$',
                 'captures': {'1': {'name': heading, 'patterns': [{'include': '#inline'}]}}},
            ]},
            'table': {'patterns': [
                rule(r'(?i)^\s*(?:atomic species\s+valence.*|site n\.\s+atom\s+positions.*|'
                     r'sticks:\s+dense.*|atom\s+type\s+.*|(?:energy|omega|frequency)\s+.*(?:sigma|cross|dos).*)$',
                     'markup.heading.table.qe-output'),
                {'match': r'^\s*(Min|Max|Sum)(?=\s+[-+.\d])', 'captures': captures(**{'1': name})},
            ]},
            'energy': {'match': r'(?i)^\s*(!?\s*total energy|the Fermi energy is|'
                      r'highest occupied(?:, lowest unoccupied)? level(?:s)?(?: \(ev\))?)\s*(=)?',
                      'captures': captures(**{'1': 'keyword.other.energy.qe-output',
                                              '2': 'keyword.operator.assignment.qe-output keyword.other.operator.qe-output'})},
            'labels': {
                'match': r'(?i)^\s*(?!Pseudo is\b|This\b|(?:URL\s+)?https?://)'
                         r'([A-Za-z][\w /().,\[\]#%+*:-]*?)\s*([=:])(?!//)(?=\s|$)(.*)$',
                'captures': {
                    '1': {'name': name, 'patterns': [{'include': '#label-content'}]},
                    '2': {'name': operator},
                    '3': {'patterns': [{'include': '#text'}]},
                },
            },
            'input': {'patterns': [
                {'match': rf'(?i)^\s*({CARDS})\b(?![ \t]*(?:\([^()\r\n]*\)[ \t]*)?=)',
                 'captures': captures(**{'1': 'keyword.control.card.qe'})},
            ]},
            'inline': {'patterns': inline},
            'label-content': {'patterns': [
                {'include': '#url'}, {'include': '#path'}, {'include': '#filename'},
                {'include': '#checksum'}, {'include': '#units'}, {'include': '#values'},
            ]},
            'assignment': {
                'match': r'\b([A-Za-z_]\w*(?:[%/:]\w+)*)(\s*(?:\([^()\n]*\)|\[[^\[\]\n]*\])*)(\s*)(=)(?![=>])',
                'captures': {
                    '1': {'name': name},
                    '2': {'name': name, 'patterns': [{'include': '#values'}]},
                    '4': {'name': operator},
                },
            },
            'url': rule(r'https?://[^\s\x22\x27<>]+', 'markup.underline.link.qe-output string.unquoted.url.qe-output'),
            'path': rule(r'(?<![\w])(?:\.{1,2}/|~/|/[\w.])[\w./+@~%=-]*', 'string.unquoted.path.qe-output'),
            'filename': rule(rf'(?i)(?<![\w/])[-\w.+@]+\.(?:{FILE_EXT})(?!\w)(?:/[^\s\x22\x27,;()<>]*)?',
                             'string.unquoted.filename.qe-output'),
            'quoted-string': rule(r'"[^"\n]*"|\x27[^\x27\n]*\x27', 'string.quoted.qe-output'),
            'checksum': rule(r'(?<!\w)[0-9a-fA-F]{32}(?:[0-9a-fA-F]{32})?(?!\w)', 'constant.numeric.hash.qe-output'),
            'time': {'patterns': [
                rule(r'\b\d{1,2}\s*(?:Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)\s*\d{4}\b',
                     'constant.numeric.date.qe-output'),
                rule(r'\b\d{1,2}:\s*\d{1,2}:\s*\d{1,2}(?:\.\d+)?\b', 'constant.numeric.time.qe-output'),
                rule(r'(?<![\w.])(?:\d+h)?(?:\d+m)?\d+(?:\.\d+)?s\b', 'constant.numeric.time.qe-output'),
            ]},
            'species': {'patterns': [
                {'match': rf'^\s*(?:(\d+)\s+)?({ELEMENT}[\w+-]*)(?=\s+(?:[-+.\d]|tau\b))',
                 'captures': captures(**{'1': 'constant.numeric.index.qe-output',
                                         '2': 'constant.language.species.qe-output'})},
                rule(rf'(?<!\w){ELEMENT}(?=\s*\()', 'constant.language.element.qe-output'),
            ]},
            'orbitals': rule(r'(?i)(?<!\w)\d+[spdfghij](?!\w)', 'constant.language.orbital.qe-output'),
            # Technical identifiers use underscores. Match their syntax rather
            # than scanning a huge variable alternation at every word in a log.
            'prose-variable': rule(r'(?<![\w./-])(?:[A-Za-z_]\w*_\w+|npool|nbgrp|nimage|ntypx|lmaxx|npk|Zval)(?![\w./-])', name),
            'units': rule(r'(?i)(?<!\w)(?:Ry|eV|Ha|a\.u\.|bohrs?|angstroms?|kbar|GPa|THz|cm-1|'
                          r'[KMGT]i?B|CPU|GPU|WALL|seconds?|minutes?|hours?|alat)(?!\w)',
                          'keyword.other.unit.qe-output'),
            'values': {'patterns': [
                rule(OUT_NUMBER, 'constant.numeric.qe-output'),
                rule(r'(?i)\b(?:TRUE|FALSE)\b', 'constant.language.boolean.qe-output'),
            ]},
            'symbols': rule(r'[=+*/<>|:&%#^~-]|[(){}\[\],;]', 'punctuation.other.qe-output keyword.other.symbol.qe-output'),
            'text': {'patterns': inline + [
                rule(r'[A-Za-z_][\w.\x27+-]*|\d+[A-Za-z_][\w.+-]*', note),
                rule(r'\S', note + ' punctuation.other.qe-output'),
            ]},
        },
    }


def build():
    for name, grammar in [('qe', input_grammar()), ('qe-output', output_grammar())]:
        path = ROOT / 'syntaxes' / f'{name}.tmLanguage.json'
        path.write_text(json.dumps(grammar, indent=2) + '\n')
        print(f'wrote {path.relative_to(ROOT)}')
    # firstLine is a JavaScript regex in VS Code, unlike TextMate rules.
    # Expand ASCII case explicitly so it also works on VS Code 1.80.
    def insensitive(name):
        return ''.join(f'[{c.upper()}{c.lower()}]' if c.isalpha() else re.escape(c) for c in name)
    package_path = ROOT / 'package.json'
    package = json.loads(package_path.read_text())
    for language in package['contributes']['languages']:
        if language['id'] == 'qe':
            language['firstLine'] = r'^\s*&(?:' + '|'.join(map(insensitive, DATA['namelists'])) + r')\b'
        if language['id'] == 'qe-output':
            language['firstLine'] = r'^\s*Program\s+(?:' + '|'.join(map(insensitive, DATA['programs'])) + r')\s+v\.[\d.]+'
    package_path.write_text(json.dumps(package, indent=2) + '\n')


if __name__ == '__main__':
    build()
