#!/usr/bin/env python3
"""Build QE TextMate grammars. Parameter assignments are syntax based so
new QE variables and utility-specific namelists work without a stale list.
References: https://www.quantum-espresso.org/documentation/input-data-description/
"""
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DATA = json.loads((ROOT / 'qe-syntax-data.json').read_text())
CARDS = '|'.join(re.escape(name) for name in sorted(DATA['cards'], key=lambda n: (-len(n), n)))
NUMBER = r'(?<![\w.])[-+]?(?:\d+\.?\d*|\.\d+)(?:[eEdD][-+]?\d+)?(?![\w.])'


def rule(regex, scope):
    return {'match': regex, 'name': scope}


def captures(**scopes):
    return {key: {'name': value} for key, value in scopes.items()}


def input_grammar():
    return {
        'name': 'Quantum ESPRESSO Input', 'scopeName': 'source.qe',
        'comment': 'Generated by tools/build_qe_grammars.py; edit the builder.',
        'patterns': [{'include': '#' + name} for name in
                     ['comments', 'strings', 'namelist', 'assignment', 'cards', 'species', 'values']],
        'repository': {
            'comments': {'patterns': [
                {'begin': '!', 'end': '$', 'name': 'comment.line.exclamation.qe'},
                {'begin': r'^\s*#', 'end': '$', 'name': 'comment.line.number-sign.qe'},
            ]},
            'strings': {'patterns': [
                {'begin': quote, 'end': quote + '|$', 'name': 'string.quoted.' + kind + '.qe',
                 'applyEndPatternLast': True,
                 'patterns': [rule(quote + quote, 'constant.character.escape.qe')]}
                for quote, kind in [("'", 'single'), ('"', 'double')]
            ]},
            'namelist': {'patterns': [
                rule(r'(?i)^\s*(?:&end\b|/)|&end\b', 'punctuation.definition.namelist.end.qe'),
                {'match': r'^\s*(&)([A-Za-z_]\w*)', 'captures': captures(**{
                    '1': 'punctuation.definition.namelist.qe', '2': 'storage.type.namelist.qe'})},
            ]},
            'cards': {'patterns': [
                {'match': rf'(?i)^\s*({CARDS})\b(?![ \t]*(?:\([^()\r\n]*\)[ \t]*)?=)',
                 'captures': captures(**{'1': 'keyword.control.card.qe'})},
                rule(r'(?i)\b(?:alat|bohr|angstrom|crystal_sg|crystal_b|crystal_c|crystal|'
                     r'tpiba_b|tpiba_c|tpiba|automatic|gamma|atomic|ortho-atomic|norm-atomic|wf|pseudo)\b',
                     'support.constant.option.qe'),
                rule(r'(?i)^\s*(?:U|J0|J|V|B|E2|E3|ALPHA)\b(?![ \t]*(?:\([^()\r\n]*\)[ \t]*)?=)',
                     'keyword.other.hubbard.qe'),
            ]},
            'assignment': {
                'match': r'(?i)\b([a-z_]\w*(?:%[a-z_]\w*)*)(\s*\([^\n()]*\))?(\s*)(=)',
                'captures': {
                    '1': {'name': 'keyword.other.variable.qe'},
                    '2': {'name': 'meta.array-index.qe', 'patterns': [{'include': '#values'}]},
                    '4': {'name': 'keyword.operator.assignment.qe'},
                },
            },
            'species': {'patterns': [
                {'match': r'^\s*([A-Za-z][\w+-]*)(?=\s+[-+.\d])',
                 'captures': captures(**{'1': 'constant.language.species.qe'})},
                rule(r'(?i)(?<![\w])[^\s\x27"!,]+\.upf\b', 'string.unquoted.pseudopotential.qe'),
                rule(r'(?i)(?<![\w])\d+[spdfghij](?![\w])', 'constant.language.orbital.qe'),
            ]},
            'values': {'patterns': [
                rule(r'(?i)\.(?:true|false|t|f)\.', 'constant.language.boolean.qe'),
                rule(NUMBER, 'constant.numeric.qe'),
                rule(r'=', 'keyword.operator.assignment.qe'),
                rule(r'(?i)\.(?:and|or|not|eqv|neqv|eq|ne|lt|le|gt|ge)\.|[*/:+<>-]', 'keyword.operator.qe'),
                rule(r',', 'punctuation.separator.qe'),
                rule(r'[(){}\[\]]', 'punctuation.section.qe'),
            ]},
        },
    }


def output_grammar():
    value_patterns = [
        rule(NUMBER, 'constant.numeric.qe-output'),
        rule(r'(?i)(?<!\w)(?:Ry|eV|Ha|a\.u\.|bohr|angstrom|kbar|GPa|THz|cm-1|CPU|WALL)(?!\w)',
             'keyword.other.unit.qe-output'),
    ]
    return {
        'name': 'Quantum ESPRESSO Output', 'scopeName': 'source.qe-output',
        'comment': 'Generated by tools/build_qe_grammars.py; edit the builder.',
        'patterns': [{'include': '#' + name} for name in
                     ['status', 'banner', 'sections', 'energy', 'labels', 'input', 'values']],
        'repository': {
            'status': {'patterns': [
                # Error delimiters frame routine diagnostics in QE outputs.
                {'begin': r'^\s*%{5,}.*$', 'end': r'^\s*%{5,}.*$',
                 'name': 'invalid.illegal.error.qe-output'},
                rule(r'(?i)^.*(?:Error in routine|convergence NOT achieved|Maximum CPU time exceeded|'
                     r'\b(?:warning|error|fatal)\b).*$','invalid.illegal.diagnostic.qe-output'),
                rule(r'(?i)^.*(?:JOB DONE\.|convergence has been achieved|End of self-consistent calculation).*$',
                     'markup.inserted.success.qe-output'),
            ]},
            'banner': {'match': r'(?i)^\s*(Program\s+\S+)\s+(v\.[\d.]+)(.*)$',
                       'captures': captures(**{'1': 'markup.heading.program.qe-output',
                                               '2': 'constant.numeric.version.qe-output'})},
            'sections': {'patterns': [
                rule(r'^\s*[-=]{5,}\s*$', 'comment.line.separator.qe-output'),
                rule(r'(?i)^\s*(?:Self-consistent Calculation|Band Structure Calculation|'
                     r'iteration #\s*\d+.*|Forces acting on atoms.*|total\s+stress.*|'
                     r'Begin final coordinates|End final coordinates|crystal axes:.*|'
                     r'reciprocal axes:.*|atomic species\s+valence.*|'
                     r'\S.*bands \(ev\):.*)\s*$', 'markup.heading.section.qe-output'),
            ]},
            'energy': {'match': r'(?i)^\s*(!?\s*total energy|the Fermi energy is|'
                      r'highest occupied(?:, lowest unoccupied)? level(?:s)?(?: \(ev\))?)\s*(=)?',
                      'captures': captures(**{'1': 'keyword.other.energy.qe-output',
                                              '2': 'keyword.operator.assignment.qe-output'})},
            'labels': {'match': r'^\s*([A-Za-z][\w /().,\[\]-]*?)\s*([=:])',
                       'captures': captures(**{'1': 'support.type.property-name.qe-output',
                                               '2': 'keyword.operator.assignment.qe-output'})},
            'input': {'patterns': [
                {'match': rf'(?i)^\s*({CARDS})\b(?![ \t]*(?:\([^()\r\n]*\)[ \t]*)?=)',
                 'captures': captures(**{'1': 'keyword.control.card.qe'})},
                {'include': 'source.qe#assignment'},
            ]},
            'values': {'patterns': value_patterns + [
                rule(r'(?i)\b(?:TRUE|FALSE)\b', 'constant.language.boolean.qe-output'),
            ]},
        },
    }


def build():
    for name, grammar in [('qe', input_grammar()), ('qe-output', output_grammar())]:
        path = ROOT / 'syntaxes' / f'{name}.tmLanguage.json'
        path.write_text(json.dumps(grammar, indent=2) + '\n')
        print(f'wrote {path.relative_to(ROOT)}')
    # firstLine is a JavaScript regex in VS Code, unlike TextMate rules.
    # Expand ASCII case explicitly so it also works on VS Code 1.80.
    def insensitive(name):
        return ''.join(f'[{c.upper()}{c.lower()}]' if c.isalpha() else re.escape(c) for c in name)
    package_path = ROOT / 'package.json'
    package = json.loads(package_path.read_text())
    for language in package['contributes']['languages']:
        if language['id'] == 'qe':
            language['firstLine'] = r'^\s*&(?:' + '|'.join(map(insensitive, DATA['namelists'])) + r')\b'
        if language['id'] == 'qe-output':
            language['firstLine'] = r'^\s*Program\s+(?:' + '|'.join(map(insensitive, DATA['programs'])) + r')\s+v\.[\d.]+'
    package_path.write_text(json.dumps(package, indent=2) + '\n')


if __name__ == '__main__':
    build()
