#!/usr/bin/env python3
"""Generate the ABINIT TextMate grammars from a single source of truth.

    python3 tools/build_grammars.py

Writes:
    syntaxes/abinit.tmLanguage.json         (source.abinit, input files)
    syntaxes/abinit-output.tmLanguage.json  (source.abinit-output, .abo/.log/...)

The list of variable names comes from tools/abinit_variables.json, which is
refreshed from the official ABINIT sources by tools/fetch_variables.py.
Edit this file (not the generated JSON) to change the highlighting rules.

Scope naming follows the TextMate conventions so that every theme renders a
coherent palette:

    ABINIT input variable      keyword.other.variable.abinit      (keyword colour)
    dataset / image suffix     constant.numeric.* / keyword.operator.*
    other named quantity       support.type.property-name.abinit  (property colour)
    numbers                    constant.numeric.*
    physical units             keyword.other.unit.abinit          (number colour)
    quoted strings, paths      string.*
    comments, separators       comment.*
    section / block titles     markup.heading.abinit
    free text in output files  comment.line.note.abinit
    errors / warnings          invalid.illegal / markup.deleted
    success messages           markup.inserted
"""

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DATA = json.loads((ROOT / "tools" / "abinit_variables.json").read_text())

# Variables accepted by older ABINIT versions (or common in old inputs) that are
# no longer part of the official database.
LEGACY_VARIABLES = ["xangst", "mkmem", "mkqmem", "mk1mem", "npkpt", "prtvolimg"]


def alternation(names):
    """Regex alternation, longest names first so that e.g. `nbandhf` beats `nband`."""
    uniq = sorted({n.lower() for n in names}, key=lambda s: (-len(s), s))
    return "|".join(uniq)


# Variables that are also plain English words: in the free text of output
# files they are almost always the word, not the variable.
ENGLISH_VARIABLES = {
    "accuracy", "alloy", "angle", "atom", "charge", "dynamics", "eta", "follow", "friction",
    "multiplicity", "order", "positron", "scissor", "slice", "structure", "surf", "temperature",
    "together", "tolerance", "vacuum", "vis",
}

VARS = alternation(DATA["variables"] + LEGACY_VARIABLES)
PROSE_VARS = alternation(v for v in DATA["variables"] + LEGACY_VARIABLES
                         if v.lower() not in ENGLISH_VARIABLES)
STRING_VARS = alternation(DATA["string_variables"])
LOGICAL_VARS = alternation(DATA["logical_variables"])
UNITS = alternation(DATA["units"])

# ---------------------------------------------------------------------------
# Shared regex fragments (Oniguruma syntax)
# ---------------------------------------------------------------------------

# A variable name must not be glued to the previous token (path, number, ...).
BEFORE = r"(?<![\w.$@/\\-])"
# Optional image suffix (_3img, _lastimg, optic's ddkfile_1) followed by the
# multi-dataset suffix: ecut12, ecut?1, ecut1?, ecut: ecut+ ecut* ecut?: ecut:? ...
SUFFIX = r"((?:_(?:\d+|last)img|_\d+)?)([0-9?]*(?:[:+*][0-9?]*)?)"
AFTER = r"(?![\w.])"

FLOAT = r"[-+]?(?:\d+\.\d*(?:[eEdD][-+]?\d+)?|\.\d+(?:[eEdD][-+]?\d+)?|\d+[eEdD][-+]?\d+)"
INT = r"[-+]?\d+"
# In output files a trailing dot is a full stop ("... in 2026."), not part of a number.
OUT_FLOAT = r"[-+]?(?:\d+\.\d+(?:[eEdD][-+]?\d+)?|\.\d+(?:[eEdD][-+]?\d+)?|\d+[eEdD][-+]?\d+)"

SUFFIX_CAPTURES = {
    "2": {"name": "keyword.other.variable.image.abinit"},
    "3": {"patterns": [
        {"match": r"\d+", "name": "constant.numeric.integer.dataset.abinit"},
        {"match": r"\?", "name": "keyword.operator.wildcard.dataset.abinit"},
        {"match": r"[:+*]", "name": "keyword.operator.series.dataset.abinit"},
    ]},
}


VARIABLE_RULE = {
    "match": rf"(?i){BEFORE}({VARS}){SUFFIX}{AFTER}",
    "captures": {"1": {"name": "keyword.other.variable.abinit"}, **SUFFIX_CAPTURES},
}


def caps(**named):
    """Build a captures dict: caps(**{'1': 'scope'}) or with dict values."""
    return {k: (v if isinstance(v, dict) else {"name": v}) for k, v in named.items()}


# ---------------------------------------------------------------------------
# Input grammar (source.abinit)
# ---------------------------------------------------------------------------

def input_grammar():
    env_var = {"match": r"\$(?:\{\w+\}|\w+)|~(?=/)", "name": "variable.other.environment.abinit"}
    return {
        "$schema": "https://raw.githubusercontent.com/martinring/tmlanguage/master/tmlanguage.json",
        "name": "ABINIT Input",
        "scopeName": "source.abinit",
        "comment": "Generated by tools/build_grammars.py -- edit that file instead.",
        "patterns": [
            {"include": "#comments"},
            {"include": "#strings"},
            {"include": "#include-directive"},
            {"include": "#namelist"},
            {"include": "#string-variable"},
            {"include": "#logical-variable"},
            {"include": "#variable"},
            {"include": "#values"},
            {"include": "#unknown-word"},
        ],
        "repository": {
            "comments": {"patterns": [
                {"name": "comment.line.number-sign.abinit", "begin": "#", "end": "$",
                 "beginCaptures": caps(**{"0": "punctuation.definition.comment.abinit"})},
                {"name": "comment.line.exclamation.abinit", "begin": "!", "end": "$",
                 "beginCaptures": caps(**{"0": "punctuation.definition.comment.abinit"})},
            ]},
            "strings": {"patterns": [
                {"name": "string.quoted.double.abinit", "begin": '"', "end": '"',
                 "beginCaptures": caps(**{"0": "punctuation.definition.string.begin.abinit"}),
                 "endCaptures": caps(**{"0": "punctuation.definition.string.end.abinit"}),
                 "patterns": [{"include": "#string-content"}]},
                {"name": "string.quoted.single.abinit", "begin": "'", "end": "'",
                 "beginCaptures": caps(**{"0": "punctuation.definition.string.begin.abinit"}),
                 "endCaptures": caps(**{"0": "punctuation.definition.string.end.abinit"}),
                 "patterns": [{"include": "#string-content"}]},
            ]},
            "string-content": {"patterns": [
                env_var,
                # structure "abifile:out_GSR.nc", "poscar:POSCAR", ...
                {"match": r"(?i)(?<=[\"'])(abifile|abivars|poscar|cif|ase)(:)",
                 "captures": caps(**{"1": "storage.type.format.abinit", "2": "punctuation.separator.abinit"})},
            ]},
            "include-directive": {
                "match": r"(?i)(?<![\w.])include(?![\w.])",
                "name": "keyword.control.import.abinit",
            },
            # Fortran namelists used by optic: &FILES ... /
            "namelist": {"patterns": [
                {"match": r"^\s*(&)(\w+)",
                 "captures": caps(**{"1": "punctuation.definition.namelist.abinit",
                                     "2": "storage.type.namelist.abinit"})},
                {"match": r"^\s*(/|&end\b)", "captures": caps(**{"1": "punctuation.definition.namelist.end.abinit"})},
                {"match": r"(?i)\.(?:true|false)\.", "name": "constant.language.boolean.abinit"},
            ]},
            # String variables whose value is written without quotes, e.g.
            # xyzfile ../geo/file.xyz   (quoted values are handled by #strings)
            "string-variable": {
                "match": rf"(?i){BEFORE}({STRING_VARS}){SUFFIX}(?:\s*(=))?\s+(?![\"'#!])([^\s#!,]+)",
                "captures": {
                    "1": {"name": "keyword.other.variable.abinit"},
                    **SUFFIX_CAPTURES,
                    "4": {"name": "keyword.operator.assignment.abinit"},
                    "5": {"name": "string.unquoted.abinit", "patterns": [env_var]},
                },
            },
            "logical-variable": {
                "match": rf"(?i){BEFORE}({LOGICAL_VARS}){SUFFIX}(?:\s*(=))?\s+([TF]|\.(?:true|false)\.){AFTER}",
                "captures": {
                    "1": {"name": "keyword.other.variable.abinit"},
                    **SUFFIX_CAPTURES,
                    "4": {"name": "keyword.operator.assignment.abinit"},
                    "5": {"name": "constant.language.boolean.abinit"},
                },
            },
            "variable": VARIABLE_RULE,
            "values": {"patterns": [
                {"include": "#units"},
                {"match": rf"(?<![\w.]){FLOAT}(?![\w.])", "name": "constant.numeric.float.abinit"},
                {"match": rf"(?<![\w.]){INT}(?![\w.])", "name": "constant.numeric.integer.abinit"},
                {"match": r"(?i)(?<![\w.])(-)?(sqrt)(?=\s*\()",
                 "captures": caps(**{"1": "keyword.operator.arithmetic.abinit",
                                     "2": "support.function.math.abinit"})},
                {"match": r"(?i)(?<![\w.])end(?![\w.])", "name": "keyword.control.end.abinit"},
                {"match": r"\*", "name": "keyword.operator.arithmetic.repeat.abinit"},
                {"match": r"/", "name": "keyword.operator.arithmetic.abinit"},
                {"match": r"=", "name": "keyword.operator.assignment.abinit"},
                {"match": r",", "name": "punctuation.separator.abinit"},
                {"match": r"[()]", "name": "punctuation.section.parens.abinit"},
            ]},
            "units": {
                "match": rf"(?i)(?<![\w.])({UNITS}){AFTER}",
                "name": "keyword.other.unit.abinit",
            },
            # Anything else that looks like a name is not a known ABINIT
            # variable (typo, or a file that is not an ABINIT input at all).
            # Consume it so that no partial highlighting appears inside it.
            "unknown-word": {
                "match": r"(?<![\w.$@/\\-])[A-Za-z_][\w]*[?:+*]*",
                "name": "meta.word.unknown.abinit",
            },
        },
    }


# ---------------------------------------------------------------------------
# Output grammar (source.abinit-output): .abo, .log, _EIG, _DDB, _DOS, ...
# ---------------------------------------------------------------------------

OUT_UNITS = (r"hartrees?|ha|m?ev|bohrs?|angstroms?|angstr|a\.u\.|au|ry|rydbergs?|kelvin|nm|gpa|"
             r"[kmg]bytes|degrees|sec|minutes|hours|fs|thz|cm-1|tesla")
FILE_EXT = (r"abi|abo|in|inc|log|out|err|files|xyz|vasp|cif|nc|psp8|psp|pspnc|psp[0-9]|upf|xml|"
            r"dat|cube|xsf|txt|pdf|agr|json|yaml|yml|sh|py|F90|f90|h5|DDB|WFK|DEN|POT")


def output_grammar():
    # Embedded (not included from source.abinit): vscode-textmate does not load
    # grammars that are only referenced from inside "captures".
    known_var = {"include": "#known-variable"}
    name_scope = "support.type.property-name.abinit"
    title_scope = "markup.heading.subsection.abinit"
    # Free text (sentences, notes, reference lists) is coloured as a comment,
    # so that the eye goes to titles, names and values first.
    note_scope = "comment.line.note.abinit"
    element = r"(?:A[cglmrstu]|B[aehikr]?|C[adeflmnorsu]?|D[bsy]|E[rsu]|F[elmr]?|G[ade]|H[efgos]?|I[nr]?|Kr?|L[airuv]|" \
              r"M[cdgnot]|N[abdehiop]?|O[gs]?|P[abdmortu]?|R[abefghnu]|S[bcegimnr]?|T[abcehilms]|U|V|W|Xe|Yb?|Z[nr])"
    return {
        "$schema": "https://raw.githubusercontent.com/martinring/tmlanguage/master/tmlanguage.json",
        "name": "ABINIT Output",
        "scopeName": "source.abinit-output",
        "comment": "Generated by tools/build_grammars.py -- edit that file instead.",
        "patterns": [
            {"include": "#yaml-document"},
            {"include": "#number-row"},
            {"include": "#line-comment"},
            {"include": "#separator"},
            {"include": "#heading"},
            {"include": "#title"},
            {"include": "#variable-echo"},
            {"include": "#dotted-label"},
            {"include": "#config-label"},
            {"include": "#label"},
            {"include": "#text"},
        ],
        "repository": {
            "known-variable": VARIABLE_RULE,
            # Rows of numbers only (eigenvalues, coordinates, densities): one
            # token for the whole row; much faster on multi-MB log files.
            "number-row": {
                "match": rf"^\s*(?:{OUT_FLOAT}|{INT})(?:\s+(?:{OUT_FLOAT}|{INT}))*\s*$",
                "name": "constant.numeric.row.abinit",
            },
            # ---------------------------------------------------------- lines
            "line-comment": {
                "match": r"^\s*#.*$",
                "name": "comment.line.number-sign.abinit",
            },
            "separator": {
                "match": r"^[\s-]?\s*([=\-+*_~])\1{9,}\s*$",
                "name": "comment.line.separator.abinit",
            },
            "heading": {"patterns": [
                # == DATASET  1 ====  /  === [ionmov= 2] Broyden...  /  ---OUTPUT---
                # --- Iteration: ( 1/100) ...  /  **** DERIVATIVE DATABASE ****
                {"match": r"^\s*(={2,}|-{3,}|\*{3,})\s*([^\s=\-*!].*?)\s*(={2,}|-{2,}>?|\*{3,})?\s*$",
                 "captures": {
                     "1": {"name": "comment.line.separator.abinit"},
                     "2": {"name": "markup.heading.abinit", "patterns": [{"include": "#heading-content"}]},
                     "3": {"name": "comment.line.separator.abinit"},
                 }},
                # -outvars: echo values of preprocessed input variables --------
                {"match": r"^\s*(-\s?outvars:.*?)\s*(-{3,})?\s*$",
                 "captures": caps(**{"1": "markup.heading.abinit", "2": "comment.line.separator.abinit"})},
                # "  ABINIT 9.10.3" at the top of the log file
                {"match": r"^\s*(ABINIT|ANADDB|OPTIC|MRGDDB|MRGDV|MRGSCR|CUT3D|MULTIBINIT|ATDEP|AIM|CONDUCTI)\s+(\d+(?:\.\d+)+)\s*$",
                 "captures": caps(**{"1": "markup.heading.abinit", "2": "constant.numeric.version.abinit"})},
                # ITER STEP NUMBER     1
                {"match": r"^\s*(ITER STEP NUMBER)\s+(\d+)\s*$",
                 "captures": caps(**{"1": "markup.heading.abinit", "2": "constant.numeric.integer.abinit"})},
                # iter   Etot(hartree)      deltaE(h)  residm     nres2
                {"match": r"^\s*iter\s+Etot\(hartree\).*$", "name": "markup.heading.table.abinit"},
                # Atom  Sphere_radius  Integrated_density
                {"match": r"^\s*Atom\s+Sphere_radius\s+Integrated_density\s*$", "name": "markup.heading.table.abinit"},
            ]},
            # Titles of the blocks that follow them.  Must stay after #heading
            # (separators) and before the label rules.
            "title": {"patterns": [
                # " Exchange-correlation functional for the present dataset will be:"
                # " cartesian forces (hartree/bohr) at end:"   " First record :"
                # " Eigenvalues (hartree) for nkpt=  18  k points:"
                # At most one space before the colon: "  GPU support    : " is an
                # empty configuration value, not a title.
                {"match": r"^[-.P_+)\s]?\s*([A-Za-z][^:\n]*?[^\s:])\s?(:)\s*$",
                 "captures": {
                     "1": {"name": title_scope, "patterns": [{"include": "#heading-content"}]},
                     "2": {"name": title_scope},
                 }},
                # " Cartesian coordinates (xcart) [bohr]"   " Reduced coordinates (xred)"
                # " Total charge density [el/bohr^3]"
                # " Cartesian forces (fcart) [Ha/bohr]; max,rms= 1.6E-02 4.4E-03 (free atoms)"
                {"match": r"^[-\s]\s?([A-Z][\w-]*(?: [\w#-]+)*)((?:\s*(?:\([^()\n]*\)|\[[^\[\]\n]*\]))+)\s*(?:(;)(.*))?$",
                 "captures": {
                     "1": {"name": title_scope, "patterns": [{"include": "#heading-content"}]},
                     "2": {"name": title_scope, "patterns": [{"include": "#heading-content"}]},
                     "3": {"name": "punctuation.separator.abinit"},
                     "4": {"patterns": [{"include": "#text"}]},
                 }},
                # Titles without a closing colon or bracket
                {"match": r"^\s*(Values of the parameters that define the memory need of the present run"
                          r"|Suggested references for the acknowledgment of ABINIT usage\."
                          r"|(?:[Rr]educed|[Cc]artesian) coordinates \(array \w+\) for\s+\d+ atoms"
                          r"|occupation numbers for kpt#\s+\d+)\s*$",
                 "captures": {"1": {"name": title_scope, "patterns": [{"include": "#heading-content"}]}}},
                # Upper-case lines of the log files: "  CALCULATING BADER CHARGE DISTRIBUTION"
                {"match": r"^\s*([A-Z][A-Z0-9-]+(?: +[A-Z][A-Z0-9()/-]*)+ *[:!]?)\s*$",
                 "captures": caps(**{"1": title_scope})},
            ]},
            # Echo of input variables:  "            acell      9.3761834869E+00 ..."
            # (optionally preceded by one of ABINIT's column-1 markers - P _),
            # the same layout in _DDB files, and the SCF lines " ETOT  3  -70.68 ..."
            "variable-echo": {
                "match": r"^[-P_ ]?\s+([a-z]\w*?|ETOT)(\d*)(?=\s+[-+]?\.?\d)",
                "captures": caps(**{"1": "keyword.other.variable.abinit",
                                    "2": "constant.numeric.integer.dataset.abinit"}),
            },
            # " FFT mesh divisions ........................   54   64  480"
            "dotted-label": {
                "match": r"^[-.P_+)\s]\s*([A-Za-z][^.:=]*?)\s*(\.{2,})(?!\.)(?=\s*(?:[-+]?\.?\d|$))",
                "captures": {
                    "1": {"name": name_scope},
                    "2": {"name": "punctuation.separator.leader.abinit"},
                },
            },
            # "  OpenMP support : yes"   "  GPU support    : "   (build information)
            "config-label": {
                "match": r"^\s*([A-Za-z][\w .()/+'-]{0,50}?)\s*(:)\s*(?:(yes|no|auto|none|enabled|disabled|ON|OFF)\s*)?$",
                "captures": {
                    "1": {"name": name_scope},
                    "2": {"name": "punctuation.separator.key-value.abinit"},
                    "3": {"name": "constant.language.abinit"},
                },
            },
            # " importxyz : Identified token ..."   "- Action: please ..."
            # "  Fortran compiler         : gnu7.3"
            "label": {
                "match": r"^[-.P_+)\s]?\s*([A-Za-z][\w .()%+/'#-]{0,60}?)\s*(:)(?=\s+\S)",
                "captures": {
                    "1": {"name": name_scope},
                    "2": {"name": "punctuation.separator.key-value.abinit"},
                },
            },
            # --------------------------------------------------------- inline
            "inline": {"patterns": [
                {"include": "#url"},
                {"include": "#quoted-string"},
                {"include": "#path"},
                {"include": "#arrow-target"},
                {"include": "#filename"},
                {"include": "#messages"},
                {"include": "#flow-mapping"},
                {"include": "#timing"},
                {"include": "#date"},
                {"include": "#inner-label"},
                {"include": "#phrase-label"},
                {"include": "#assignment"},
                {"include": "#trailing-names"},
                {"include": "#symmetry"},
                {"include": "#pseudopotential"},
                {"include": "#units"},
                {"include": "#numbers"},
                {"include": "#brackets"},
            ]},
            # inside titles: no free-text colour, which would hide the title colour
            "heading-content": {"patterns": [
                {"include": "#inline"},
                {"include": "#prose-variable"},
            ]},
            # everything else: the rest of a line
            "text": {"patterns": [
                # column-1 markers of ABINIT's output: "P This job should need ..."
                {"match": r"^[P_](?=\s)", "name": "punctuation.definition.marker.abinit"},
                # brackets of sentences take the colour of the sentence
                {"match": r"[()\[\]]", "name": f"{note_scope} punctuation.section.brackets.abinit"},
                {"include": "#inline"},
                {"include": "#prose-variable"},
                {"include": "#note"},
            ]},
            # "... etot is converged",  "decrease tolsym to ...": variables in
            # sentences (case-sensitive, and not the ones that are English words)
            "prose-variable": {
                "match": rf"\b(?<![.$@/\\-])(?:{PROSE_VARS})(?![\w#]|\.\w)",
                "name": "keyword.other.variable.abinit",
            },
            "note": {
                "match": r"[A-Za-z_][\w'#+-]*(?:\.\w+)*|\d+[A-Za-z_][\w'#+-]*",
                "name": note_scope,
            },
            # Thu 16 Apr 2026 / Thu Apr 16 13:58:21 2026 / Jul 2023 / 08/19/23 / 13h58
            "date": {"patterns": [
                {"match": r"\b(?:Mon|Tue|Wed|Thu|Fri|Sat|Sun)\s+(?:\d{1,2}\s+)?"
                          r"(?:Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)(?:\s+\d{1,2})?"
                          r"(?:\s+\d{1,2}:\d\d(?::\d\d)?)?\s+\d{4}\b",
                 "name": "constant.numeric.date.abinit"},
                {"match": r"\b(?:Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)\s+\d{4}\b",
                 "name": "constant.numeric.date.abinit"},
                {"match": r"(?<![\w/.])\d{1,2}/\d{1,2}/\d{2,4}(?![\w/])", "name": "constant.numeric.date.abinit"},
                {"match": r"(?<![\w.])\d{1,2}h\d\d(?![\w])", "name": "constant.numeric.time.abinit"},
                # md5 checksums at the end of the log
                {"match": r"(?<!\w)[0-9a-f]{32,64}(?!\w)", "name": "constant.numeric.hash.abinit"},
            ]},
            # "... ; DEN or POT disk file :  12.658 Mbytes."   "mpi_nproc: 16, omp_nthreads: 1"
            "inner-label": {
                "match": r"(?<=;\s|,\s)([A-Za-z][\w ]{0,40}?)\s*(:)(?=\s+\S)",
                "captures": {
                    "1": {"name": name_scope, "patterns": [known_var]},
                    "2": {"name": "punctuation.separator.key-value.abinit"},
                },
            },
            # The words describing a value:  " Unit cell volume ucvol= ..."
            # " Fermi (or HOMO) energy (hartree) = ...   Average Vxc (hartree)= ..."
            # " Total energy (etotal) [Ha]= ..."  "; Volume of real space cell (bohr^3)= ..."
            "phrase-label": {
                "match": r"(?:^[-.P_+)\s]?\s*|(?<=\s\s|;\s|,\s))"
                         r"(?!(?:i\.e|e\.g|cf)\.)"  # "i.e. iomode=3" is a sentence
                         r"((?:(?:[A-Za-z][A-Za-z#.'-]*|\([^()=\n]*\))\s+){1,5}?)"
                         r"(?=[A-Za-z_][\w#]*(?:[,/][A-Za-z_][\w#]*)*"
                         r"(?:\s?(?:\([^()=<>\n]*\)|\[[^\[\]=<>\n]*\]))*\s*=(?![=>]))",
                "captures": {"1": {"name": name_scope, "patterns": [
                    known_var, {"include": "#units"}, {"include": "#brackets"}]}},
            },
            # "   170504        znucl, zion, pspdat"   "... ecore*ucvol(ha*bohr**3)"
            "trailing-names": {"patterns": [
                {"match": r"(?<=\s\s)([a-z]\w*(?:\s*,\s*[a-z]\w*)+)\s*$",
                 "captures": {"1": {"name": name_scope, "patterns": [known_var]}}},
                {"match": r"(?<=\s\s)([a-z]\w*(?:\*[a-z]\w*)+)(\([^()\n]*\))\s*$",
                 "captures": {
                     "1": {"name": name_scope, "patterns": [known_var]},
                     "2": {"name": name_scope, "patterns": [{"include": "#units"}, {"include": "#brackets"}]},
                 }},
                {"match": r"(?<![\w])kpt#", "name": name_scope},
            ]},
            # space group Pm (# 6); Bravais mP   /   the Bravais lattice is oP
            "symmetry": {
                "match": r"(?<=space group |Bravais |lattice is )[A-Za-z][\w/^-]*",
                "name": "constant.language.symmetry.abinit",
            },
            # "- Al    ONCVPSP-3.2.3.1  r_core= ..."   " znucl=N     ONCVPSP-3.2.3.1"
            "pseudopotential": {
                "match": rf"(?<![\w.-])(?:({element})\s+)?(ONCVPSP|ATOMPAW|FHI98PP|HGH|GTH|Troullier-Martins)(?=[-\s]|$)",
                "captures": {
                    "1": {"name": "constant.language.element.abinit"},
                    "2": {"name": name_scope},
                },
            },
            # Brackets have no colour of their own: they take the colour of the
            # title, name or sentence around them (VS Code's bracket-pair colours
            # are switched off for this language in language-configuration-output.json).
            "brackets": {
                "match": r"[()\[\]]",
                "name": "punctuation.section.brackets.abinit",
            },
            "url": {
                "match": r"\b(?:https?|ftp)://[^\s<>\"')\]]*[^\s<>\"').,;:\]]",
                # link colour on top of the underline (some themes only underline links)
                "name": "markup.underline.link.abinit string.other.link.abinit",
            },
            "quoted-string": {"patterns": [
                {"match": r"\"[^\"\n]*\"", "name": "string.quoted.double.abinit"},
                {"match": r"(?<![\w])'[^'\n]*'(?![\w])", "name": "string.quoted.single.abinit"},
            ]},
            "path": {
                "match": r"(?:(?<=[\s(=:,])|^)(?:~\w*|\.{1,2})?/[\w.+~@%-]+(?:/[\w.+~@%-]*)*",
                "name": "string.unquoted.path.abinit",
            },
            # - input  file    -> run.abi   /  root for output files -> runo
            "arrow-target": {
                "match": r"(?<![-=<])(->)\s*([^\s<>-]\S*)",
                "captures": caps(**{"1": "keyword.operator.arrow.abinit", "2": "string.unquoted.path.abinit"}),
            },
            "filename": {"patterns": [
                {"match": rf"(?<![\w./-])[\w+-][\w.+-]*\.(?:{FILE_EXT})(?![\w.])",
                 "name": "string.unquoted.filename.abinit"},
                # ABINIT output files: runo_EIG, runo_DS2_WFK, out_GSR.nc ...
                {"match": r"(?<![\w./-])[a-z][\w-]*?_(?:DS\d+_)?(?:TIM\d+_)?[A-Z][A-Z0-9]*(?:_[A-Z][A-Z0-9]*)*(?:\.nc)?(?![\w.])",
                 "name": "string.unquoted.filename.abinit"},
            ]},
            "messages": {"patterns": [
                {"match": r"\b(?:ERROR|BUG|FATAL|Error)\b", "name": "invalid.illegal.error.abinit"},
                {"match": r"\bWARNINGs?\b", "name": "markup.deleted.warning.abinit"},
                {"match": r"\bCOMMENTs?\b", "name": "markup.changed.comment.abinit"},
                {"match": r"\b(?:Calculation completed\.|(?:is|are) converged\b|convergence reached)",
                 "name": "markup.inserted.success.abinit"},
                {"match": r"\b(?:not converged|have not converged yet)\b", "name": "markup.deleted.warning.abinit"},
            ]},
            # {SCF_istep: 1 , Vnl|psi>: 1.2 , wall_time: ' 0:14 [minutes] '}
            "flow-mapping": {
                "begin": r"\{", "end": r"\}",
                "beginCaptures": caps(**{"0": f"{name_scope} punctuation.definition.mapping.begin.abinit"}),
                "endCaptures": caps(**{"0": f"{name_scope} punctuation.definition.mapping.end.abinit"}),
                "patterns": [{"include": "#yaml-flow-content"}],
            },
            "timing": {"match": r"<<<\s*TIME\b.*$", "name": "comment.line.timing.abinit"},
            # name= value, including  ecut(hartree)=  sigma(1 1)=  frms,max,avg=
            "assignment": {
                "match": r"(?<![\w)\]#-])(?<!\w\.)([A-Za-z_][\w#]*(?:[,/][A-Za-z_][\w#]*)*)"
                         r"((?:\s?(?:\([^()=<>\n]*\)|\[[^\[\]=<>\n]*\]))*)\s*(=)(?![=>])",
                "captures": {
                    "1": {"name": name_scope, "patterns": [known_var]},
                    "2": {"name": name_scope, "patterns": [known_var, {"include": "#units"}, {"include": "#numbers"},
                                       {"include": "#brackets"},
                                       {"match": r"[A-Za-z_]\w*", "name": name_scope}]},
                    "3": {"name": "keyword.operator.assignment.abinit"},
                },
            },
            "units": {
                "match": rf"(?i)(?<![\w.])(?:{OUT_UNITS})(?:\^-?\d+|\*\*\d+)?(?![\w])",
                "name": "keyword.other.unit.abinit",
            },
            "numbers": {"patterns": [
                {"match": r"(?<![\w.])\d+(?:\.\d+){2,}(?![\w.])", "name": "constant.numeric.version.abinit"},
                {"match": r"(?<![\w:.])\d{1,3}:\d\d(?::\d\d)?(?![\w:])", "name": "constant.numeric.time.abinit"},
                {"match": rf"(?<![\w.]){OUT_FLOAT}(?![\w])", "name": "constant.numeric.float.abinit"},
                {"match": rf"(?<![\w.]){INT}(?![\w])", "name": "constant.numeric.integer.abinit"},
                {"match": r"\b(?:NaN|Infinity)\b", "name": "invalid.illegal.nan.abinit"},
            ]},
            # ----------------------------------------------------------- YAML
            # --- !ResultsGS ... '...'   (also !WARNING, !COMMENT, !ERROR)
            "yaml-document": {
                "name": "meta.document.yaml.abinit",
                "begin": r"^(---)\s*(!)(\w+)(.*)$",
                "beginCaptures": {
                    "1": {"name": "comment.line.separator.abinit"},
                    "2": {"name": "punctuation.definition.tag.abinit"},
                    "3": {"patterns": [
                        {"match": r"ERROR|BUG", "name": "invalid.illegal.error.abinit"},
                        {"match": r"WARNING", "name": "markup.deleted.warning.abinit"},
                        {"match": r"COMMENT", "name": "markup.changed.comment.abinit"},
                        {"match": r"\w+", "name": "markup.heading.document.abinit"},
                    ]},
                },
                "end": r"^(\.\.\.)\s*$|(?=^---\s*!)",
                "endCaptures": caps(**{"1": "comment.line.separator.abinit"}),
                "patterns": [
                    {"include": "#yaml-block-scalar"},
                    {"include": "#yaml-comment"},
                    {"include": "#yaml-key"},
                    {"include": "#yaml-sequence"},
                    {"include": "#yaml-flow-content"},
                ],
            },
            # message: |    (indented free text until the next non-indented line)
            "yaml-block-scalar": {
                "begin": r"^(\s*)([\w-]+)\s*(:)\s*([|>][-+]?)\s*$",
                "beginCaptures": {
                    "2": {"name": name_scope},
                    "3": {"name": "punctuation.separator.key-value.abinit"},
                    "4": {"name": "keyword.control.flow.block-scalar.abinit"},
                },
                "while": r"^(?=\s|$)",
                "patterns": [{"include": "#text"}],
            },
            "yaml-comment": {
                "match": r"(?:^|(?<=\s))#.*$",
                "name": "comment.line.number-sign.abinit",
            },
            "yaml-key": {
                "match": r"^(\s*)(?:(-)\s+)?('[^']*'|\"[^\"]*\"|[A-Za-z_][\w .()/*+-]*?)\s*(:)(?=\s|$)",
                "captures": {
                    "2": {"name": "punctuation.definition.sequence.item.abinit"},
                    "3": {"name": name_scope, "patterns": [known_var]},
                    "4": {"name": "punctuation.separator.key-value.abinit"},
                },
            },
            "yaml-sequence": {
                "match": r"^\s*(-)(?=\s)",
                "captures": caps(**{"1": "punctuation.definition.sequence.item.abinit"}),
            },
            "yaml-flow-content": {"patterns": [
                {"include": "#yaml-comment"},
                {"include": "#quoted-string"},
                {"match": r"([A-Za-z_][\w|>]*)\s*(:)(?=\s)",
                 "captures": {
                     "1": {"name": name_scope, "patterns": [known_var]},
                     "2": {"name": "punctuation.separator.key-value.abinit"},
                 }},
                {"match": r"\b(?:null|true|false|yes|no)\b", "name": "constant.language.abinit"},
                # xred: - [ -1.9086E-08, -1.0530E-11, 3.1929E-01, Al]
                {"match": rf"(?<=,)\s*({element})(?=\s*\])",
                 "captures": caps(**{"1": "constant.language.element.abinit"})},
                # braces and brackets of YAML values: the colour of the keys
                {"match": r"[\[\]{}]", "name": f"{name_scope} punctuation.definition.collection.abinit"},
                {"match": r",", "name": "punctuation.separator.abinit"},
                {"include": "#text"},
            ]},
        },
    }


def write(name, grammar):
    path = ROOT / "syntaxes" / name
    path.write_text(json.dumps(grammar, indent=2, ensure_ascii=False) + "\n")
    print(f"wrote {path.relative_to(ROOT)} ({path.stat().st_size // 1024} KiB)")


if __name__ == "__main__":
    write("abinit.tmLanguage.json", input_grammar())
    write("abinit-output.tmLanguage.json", output_grammar())
