#!/usr/bin/env python3
"""Generate the ABINIT TextMate grammars from a single source of truth.

    python3 tools/build_grammars.py

Writes:
    syntaxes/abinit.tmLanguage.json         (source.abinit, input files)
    syntaxes/abinit-output.tmLanguage.json  (source.abinit-output, .abo/.log/...)

The list of variable names comes from tools/abinit_variables.json, which is
refreshed from the official ABINIT sources by tools/fetch_variables.py.
Edit this file (not the generated JSON) to change the highlighting rules.

Scope naming follows the TextMate conventions so that every theme renders a
coherent palette:

    ABINIT input variable      keyword.other.variable.abinit      (keyword colour)
    dataset / image suffix     constant.numeric.* / keyword.operator.*
    other named quantity       support.type.property-name.abinit  (property colour)
    numbers                    constant.numeric.*
    physical units             keyword.other.unit.abinit          (number colour)
    quoted strings, paths      string.*
    comments, separators       comment.*
    section titles             markup.heading.abinit
    errors / warnings          invalid.illegal / markup.deleted
    success messages           markup.inserted
"""

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DATA = json.loads((ROOT / "tools" / "abinit_variables.json").read_text())

# Variables accepted by older ABINIT versions (or common in old inputs) that are
# no longer part of the official database.
LEGACY_VARIABLES = ["xangst", "mkmem", "mkqmem", "mk1mem", "npkpt", "prtvolimg"]


def alternation(names):
    """Regex alternation, longest names first so that e.g. `nbandhf` beats `nband`."""
    uniq = sorted({n.lower() for n in names}, key=lambda s: (-len(s), s))
    return "|".join(uniq)


VARS = alternation(DATA["variables"] + LEGACY_VARIABLES)
STRING_VARS = alternation(DATA["string_variables"])
LOGICAL_VARS = alternation(DATA["logical_variables"])
UNITS = alternation(DATA["units"])

# ---------------------------------------------------------------------------
# Shared regex fragments (Oniguruma syntax)
# ---------------------------------------------------------------------------

# A variable name must not be glued to the previous token (path, number, ...).
BEFORE = r"(?<![\w.$@/\\-])"
# Optional image suffix (_3img, _lastimg, optic's ddkfile_1) followed by the
# multi-dataset suffix: ecut12, ecut?1, ecut1?, ecut: ecut+ ecut* ecut?: ecut:? ...
SUFFIX = r"((?:_(?:\d+|last)img|_\d+)?)([0-9?]*(?:[:+*][0-9?]*)?)"
AFTER = r"(?![\w.])"

FLOAT = r"[-+]?(?:\d+\.\d*(?:[eEdD][-+]?\d+)?|\.\d+(?:[eEdD][-+]?\d+)?|\d+[eEdD][-+]?\d+)"
INT = r"[-+]?\d+"
# In output files a trailing dot is a full stop ("... in 2026."), not part of a number.
OUT_FLOAT = r"[-+]?(?:\d+\.\d+(?:[eEdD][-+]?\d+)?|\.\d+(?:[eEdD][-+]?\d+)?|\d+[eEdD][-+]?\d+)"

SUFFIX_CAPTURES = {
    "2": {"name": "keyword.other.variable.image.abinit"},
    "3": {"patterns": [
        {"match": r"\d+", "name": "constant.numeric.integer.dataset.abinit"},
        {"match": r"\?", "name": "keyword.operator.wildcard.dataset.abinit"},
        {"match": r"[:+*]", "name": "keyword.operator.series.dataset.abinit"},
    ]},
}


VARIABLE_RULE = {
    "match": rf"(?i){BEFORE}({VARS}){SUFFIX}{AFTER}",
    "captures": {"1": {"name": "keyword.other.variable.abinit"}, **SUFFIX_CAPTURES},
}


def caps(**named):
    """Build a captures dict: caps(**{'1': 'scope'}) or with dict values."""
    return {k: (v if isinstance(v, dict) else {"name": v}) for k, v in named.items()}


# ---------------------------------------------------------------------------
# Input grammar (source.abinit)
# ---------------------------------------------------------------------------

def input_grammar():
    env_var = {"match": r"\$(?:\{\w+\}|\w+)|~(?=/)", "name": "variable.other.environment.abinit"}
    return {
        "$schema": "https://raw.githubusercontent.com/martinring/tmlanguage/master/tmlanguage.json",
        "name": "ABINIT Input",
        "scopeName": "source.abinit",
        "comment": "Generated by tools/build_grammars.py -- edit that file instead.",
        "patterns": [
            {"include": "#comments"},
            {"include": "#strings"},
            {"include": "#include-directive"},
            {"include": "#namelist"},
            {"include": "#string-variable"},
            {"include": "#logical-variable"},
            {"include": "#variable"},
            {"include": "#values"},
            {"include": "#unknown-word"},
        ],
        "repository": {
            "comments": {"patterns": [
                {"name": "comment.line.number-sign.abinit", "begin": "#", "end": "$",
                 "beginCaptures": caps(**{"0": "punctuation.definition.comment.abinit"})},
                {"name": "comment.line.exclamation.abinit", "begin": "!", "end": "$",
                 "beginCaptures": caps(**{"0": "punctuation.definition.comment.abinit"})},
            ]},
            "strings": {"patterns": [
                {"name": "string.quoted.double.abinit", "begin": '"', "end": '"',
                 "beginCaptures": caps(**{"0": "punctuation.definition.string.begin.abinit"}),
                 "endCaptures": caps(**{"0": "punctuation.definition.string.end.abinit"}),
                 "patterns": [{"include": "#string-content"}]},
                {"name": "string.quoted.single.abinit", "begin": "'", "end": "'",
                 "beginCaptures": caps(**{"0": "punctuation.definition.string.begin.abinit"}),
                 "endCaptures": caps(**{"0": "punctuation.definition.string.end.abinit"}),
                 "patterns": [{"include": "#string-content"}]},
            ]},
            "string-content": {"patterns": [
                env_var,
                # structure "abifile:out_GSR.nc", "poscar:POSCAR", ...
                {"match": r"(?i)(?<=[\"'])(abifile|abivars|poscar|cif|ase)(:)",
                 "captures": caps(**{"1": "storage.type.format.abinit", "2": "punctuation.separator.abinit"})},
            ]},
            "include-directive": {
                "match": r"(?i)(?<![\w.])include(?![\w.])",
                "name": "keyword.control.import.abinit",
            },
            # Fortran namelists used by optic: &FILES ... /
            "namelist": {"patterns": [
                {"match": r"^\s*(&)(\w+)",
                 "captures": caps(**{"1": "punctuation.definition.namelist.abinit",
                                     "2": "storage.type.namelist.abinit"})},
                {"match": r"^\s*(/|&end\b)", "captures": caps(**{"1": "punctuation.definition.namelist.end.abinit"})},
                {"match": r"(?i)\.(?:true|false)\.", "name": "constant.language.boolean.abinit"},
            ]},
            # String variables whose value is written without quotes, e.g.
            # xyzfile ../geo/file.xyz   (quoted values are handled by #strings)
            "string-variable": {
                "match": rf"(?i){BEFORE}({STRING_VARS}){SUFFIX}(?:\s*(=))?\s+(?![\"'#!])([^\s#!,]+)",
                "captures": {
                    "1": {"name": "keyword.other.variable.abinit"},
                    **SUFFIX_CAPTURES,
                    "4": {"name": "keyword.operator.assignment.abinit"},
                    "5": {"name": "string.unquoted.abinit", "patterns": [env_var]},
                },
            },
            "logical-variable": {
                "match": rf"(?i){BEFORE}({LOGICAL_VARS}){SUFFIX}(?:\s*(=))?\s+([TF]|\.(?:true|false)\.){AFTER}",
                "captures": {
                    "1": {"name": "keyword.other.variable.abinit"},
                    **SUFFIX_CAPTURES,
                    "4": {"name": "keyword.operator.assignment.abinit"},
                    "5": {"name": "constant.language.boolean.abinit"},
                },
            },
            "variable": VARIABLE_RULE,
            "values": {"patterns": [
                {"include": "#units"},
                {"match": rf"(?<![\w.]){FLOAT}(?![\w.])", "name": "constant.numeric.float.abinit"},
                {"match": rf"(?<![\w.]){INT}(?![\w.])", "name": "constant.numeric.integer.abinit"},
                {"match": r"(?i)(?<![\w.])(-)?(sqrt)(?=\s*\()",
                 "captures": caps(**{"1": "keyword.operator.arithmetic.abinit",
                                     "2": "support.function.math.abinit"})},
                {"match": r"(?i)(?<![\w.])end(?![\w.])", "name": "keyword.control.end.abinit"},
                {"match": r"\*", "name": "keyword.operator.arithmetic.repeat.abinit"},
                {"match": r"/", "name": "keyword.operator.arithmetic.abinit"},
                {"match": r"=", "name": "keyword.operator.assignment.abinit"},
                {"match": r",", "name": "punctuation.separator.abinit"},
                {"match": r"[()]", "name": "punctuation.section.parens.abinit"},
            ]},
            "units": {
                "match": rf"(?i)(?<![\w.])({UNITS}){AFTER}",
                "name": "keyword.other.unit.abinit",
            },
            # Anything else that looks like a name is not a known ABINIT
            # variable (typo, or a file that is not an ABINIT input at all).
            # Consume it so that no partial highlighting appears inside it.
            "unknown-word": {
                "match": r"(?<![\w.$@/\\-])[A-Za-z_][\w]*[?:+*]*",
                "name": "meta.word.unknown.abinit",
            },
        },
    }


# ---------------------------------------------------------------------------
# Output grammar (source.abinit-output): .abo, .log, _EIG, _DDB, _DOS, ...
# ---------------------------------------------------------------------------

OUT_UNITS = (r"hartrees?|ha|m?ev|bohrs?|angstroms?|angstr|a\.u\.|au|ry|rydbergs?|kelvin|nm|gpa|"
             r"[kmg]bytes|degrees|sec|minutes|hours|fs|thz|cm-1|tesla")
FILE_EXT = (r"abi|abo|in|inc|log|out|err|files|xyz|vasp|cif|nc|psp8|psp|pspnc|psp[0-9]|upf|xml|"
            r"dat|cube|xsf|txt|pdf|agr|json|yaml|yml|sh|py|F90|f90|h5|DDB|WFK|DEN|POT")


def output_grammar():
    # Embedded (not included from source.abinit): vscode-textmate does not load
    # grammars that are only referenced from inside "captures".
    known_var = {"include": "#known-variable"}
    name_scope = "support.type.property-name.abinit"
    return {
        "$schema": "https://raw.githubusercontent.com/martinring/tmlanguage/master/tmlanguage.json",
        "name": "ABINIT Output",
        "scopeName": "source.abinit-output",
        "comment": "Generated by tools/build_grammars.py -- edit that file instead.",
        "patterns": [
            {"include": "#yaml-document"},
            {"include": "#line-comment"},
            {"include": "#separator"},
            {"include": "#heading"},
            {"include": "#variable-echo"},
            {"include": "#dotted-label"},
            {"include": "#label"},
            {"include": "#inline"},
        ],
        "repository": {
            "known-variable": VARIABLE_RULE,
            # ---------------------------------------------------------- lines
            "line-comment": {
                "match": r"^\s*#.*$",
                "name": "comment.line.number-sign.abinit",
            },
            "separator": {
                "match": r"^[\s-]?\s*([=\-+*_~])\1{9,}\s*$",
                "name": "comment.line.separator.abinit",
            },
            "heading": {"patterns": [
                # == DATASET  1 ====  /  === [ionmov= 2] Broyden...  /  ---OUTPUT---
                # --- Iteration: ( 1/100) ...  /  **** DERIVATIVE DATABASE ****
                {"match": r"^\s*(={2,}|-{3,}|\*{3,})\s*([^\s=\-*!].*?)\s*(={2,}|-{2,}>?|\*{3,})?\s*$",
                 "captures": {
                     "1": {"name": "comment.line.separator.abinit"},
                     "2": {"name": "markup.heading.abinit", "patterns": [{"include": "#inline"}]},
                     "3": {"name": "comment.line.separator.abinit"},
                 }},
                # -outvars: echo values of preprocessed input variables --------
                {"match": r"^\s*(-\s?outvars:.*?)\s*(-{3,})?\s*$",
                 "captures": caps(**{"1": "markup.heading.abinit", "2": "comment.line.separator.abinit"})},
                # "  ABINIT 9.10.3" at the top of the log file
                {"match": r"^\s*(ABINIT|ANADDB|OPTIC|MRGDDB|MRGDV|MRGSCR|CUT3D|MULTIBINIT|ATDEP|AIM|CONDUCTI)\s+(\d+(?:\.\d+)+)\s*$",
                 "captures": caps(**{"1": "markup.heading.abinit", "2": "constant.numeric.version.abinit"})},
                # ITER STEP NUMBER     1
                {"match": r"^\s*(ITER STEP NUMBER)\s+(\d+)\s*$",
                 "captures": caps(**{"1": "markup.heading.abinit", "2": "constant.numeric.integer.abinit"})},
                # iter   Etot(hartree)      deltaE(h)  residm     nres2
                {"match": r"^\s*iter\s+Etot\(hartree\).*$", "name": "markup.heading.table.abinit"},
            ]},
            # Echo of input variables:  "            acell      9.3761834869E+00 ..."
            # (optionally preceded by one of ABINIT's column-1 markers - P _),
            # the same layout in _DDB files, and the SCF lines " ETOT  3  -70.68 ..."
            "variable-echo": {
                "match": r"^[-P_ ]?\s+([a-z]\w*?|ETOT)(\d*)(?=\s+[-+]?\.?\d)",
                "captures": caps(**{"1": "keyword.other.variable.abinit",
                                    "2": "constant.numeric.integer.dataset.abinit"}),
            },
            # " FFT mesh divisions ........................   54   64  480"
            "dotted-label": {
                "match": r"^[-.P_+)\s]\s*([A-Za-z][^.:=]*?)\s*(\.{2,})(?!\.)(?=\s*(?:[-+]?\.?\d|$))",
                "captures": {
                    "1": {"name": name_scope},
                    "2": {"name": "punctuation.separator.leader.abinit"},
                },
            },
            # " importxyz : Identified token ..."   "- Action: please ..."
            # "  Fortran compiler         : gnu7.3"
            "label": {
                "match": r"^[-.P_+)\s]?\s*([A-Za-z][\w .()%+/'#-]{0,60}?)\s*(:)(?=\s+\S)",
                "captures": {
                    "1": {"name": name_scope},
                    "2": {"name": "punctuation.separator.key-value.abinit"},
                },
            },
            # --------------------------------------------------------- inline
            "inline": {"patterns": [
                {"include": "#url"},
                {"include": "#quoted-string"},
                {"include": "#path"},
                {"include": "#arrow-target"},
                {"include": "#filename"},
                {"include": "#messages"},
                {"include": "#flow-mapping"},
                {"include": "#timing"},
                {"include": "#assignment"},
                {"include": "#units"},
                {"include": "#numbers"},
            ]},
            "url": {
                "match": r"\b(?:https?|ftp)://[^\s<>\"')\]]*[^\s<>\"').,;:\]]",
                "name": "markup.underline.link.abinit",
            },
            "quoted-string": {"patterns": [
                {"match": r"\"[^\"\n]*\"", "name": "string.quoted.double.abinit"},
                {"match": r"(?<![\w])'[^'\n]*'(?![\w])", "name": "string.quoted.single.abinit"},
            ]},
            "path": {
                "match": r"(?:(?<=[\s(=:,])|^)(?:~\w*|\.{1,2})?/[\w.+~@%-]+(?:/[\w.+~@%-]*)*",
                "name": "string.unquoted.path.abinit",
            },
            # - input  file    -> run.abi   /  root for output files -> runo
            "arrow-target": {
                "match": r"(?<![-=<])(->)\s*([^\s<>-]\S*)",
                "captures": caps(**{"1": "keyword.operator.arrow.abinit", "2": "string.unquoted.path.abinit"}),
            },
            "filename": {"patterns": [
                {"match": rf"(?<![\w./-])[\w+-][\w.+-]*\.(?:{FILE_EXT})(?![\w.])",
                 "name": "string.unquoted.filename.abinit"},
                # ABINIT output files: runo_EIG, runo_DS2_WFK, out_GSR.nc ...
                {"match": r"(?<![\w./-])[a-z][\w-]*?_(?:DS\d+_)?(?:TIM\d+_)?[A-Z][A-Z0-9]*(?:_[A-Z][A-Z0-9]*)*(?:\.nc)?(?![\w.])",
                 "name": "string.unquoted.filename.abinit"},
            ]},
            "messages": {"patterns": [
                {"match": r"\b(?:ERROR|BUG|FATAL|Error)\b", "name": "invalid.illegal.error.abinit"},
                {"match": r"\bWARNINGs?\b", "name": "markup.deleted.warning.abinit"},
                {"match": r"\bCOMMENTs?\b", "name": "markup.changed.comment.abinit"},
                {"match": r"\b(?:Calculation completed\.|(?:is|are) converged\b|convergence reached)",
                 "name": "markup.inserted.success.abinit"},
                {"match": r"\b(?:not converged|have not converged yet)\b", "name": "markup.deleted.warning.abinit"},
            ]},
            # {SCF_istep: 1 , Vnl|psi>: 1.2 , wall_time: ' 0:14 [minutes] '}
            "flow-mapping": {
                "begin": r"\{", "end": r"\}",
                "beginCaptures": caps(**{"0": "punctuation.definition.mapping.begin.abinit"}),
                "endCaptures": caps(**{"0": "punctuation.definition.mapping.end.abinit"}),
                "patterns": [{"include": "#yaml-flow-content"}],
            },
            "timing": {"match": r"<<<\s*TIME\b.*$", "name": "comment.line.timing.abinit"},
            # name= value, including  ecut(hartree)=  sigma(1 1)=  frms,max,avg=
            "assignment": {
                "match": r"(?<![\w)\]#-])(?<!\w\.)([A-Za-z_][\w#]*(?:,[A-Za-z_][\w#]*)*)(\s?\([^()=<>\n]*\))?\s*(=)(?![=>])",
                "captures": {
                    "1": {"name": name_scope, "patterns": [known_var]},
                    "2": {"patterns": [{"include": "#units"}, {"include": "#numbers"}]},
                    "3": {"name": "keyword.operator.assignment.abinit"},
                },
            },
            "units": {
                "match": rf"(?i)(?<![\w.])(?:{OUT_UNITS})(?:\^-?\d+|\*\*\d+)?(?![\w])",
                "name": "keyword.other.unit.abinit",
            },
            "numbers": {"patterns": [
                {"match": r"(?<![\w.])\d+(?:\.\d+){2,}(?![\w.])", "name": "constant.numeric.version.abinit"},
                {"match": r"(?<![\w:.])\d{1,3}:\d\d(?::\d\d)?(?![\w:])", "name": "constant.numeric.time.abinit"},
                {"match": rf"(?<![\w.]){OUT_FLOAT}(?![\w])", "name": "constant.numeric.float.abinit"},
                {"match": rf"(?<![\w.]){INT}(?![\w])", "name": "constant.numeric.integer.abinit"},
                {"match": r"\b(?:NaN|Infinity)\b", "name": "invalid.illegal.nan.abinit"},
            ]},
            # ----------------------------------------------------------- YAML
            # --- !ResultsGS ... '...'   (also !WARNING, !COMMENT, !ERROR)
            "yaml-document": {
                "name": "meta.document.yaml.abinit",
                "begin": r"^(---)\s*(!)(\w+)(.*)$",
                "beginCaptures": {
                    "1": {"name": "comment.line.separator.abinit"},
                    "2": {"name": "punctuation.definition.tag.abinit"},
                    "3": {"patterns": [
                        {"match": r"ERROR|BUG", "name": "invalid.illegal.error.abinit"},
                        {"match": r"WARNING", "name": "markup.deleted.warning.abinit"},
                        {"match": r"COMMENT", "name": "markup.changed.comment.abinit"},
                        {"match": r"\w+", "name": "markup.heading.document.abinit"},
                    ]},
                },
                "end": r"^(\.\.\.)\s*$|(?=^---\s*!)",
                "endCaptures": caps(**{"1": "comment.line.separator.abinit"}),
                "patterns": [
                    {"include": "#yaml-block-scalar"},
                    {"include": "#yaml-comment"},
                    {"include": "#yaml-key"},
                    {"include": "#yaml-sequence"},
                    {"include": "#yaml-flow-content"},
                ],
            },
            # message: |    (indented free text until the next non-indented line)
            "yaml-block-scalar": {
                "begin": r"^(\s*)([\w-]+)\s*(:)\s*([|>][-+]?)\s*$",
                "beginCaptures": {
                    "2": {"name": name_scope},
                    "3": {"name": "punctuation.separator.key-value.abinit"},
                    "4": {"name": "keyword.control.flow.block-scalar.abinit"},
                },
                "while": r"^(?=\s|$)",
                "patterns": [{"include": "#inline"}],
            },
            "yaml-comment": {
                "match": r"(?:^|(?<=\s))#.*$",
                "name": "comment.line.number-sign.abinit",
            },
            "yaml-key": {
                "match": r"^(\s*)(?:(-)\s+)?('[^']*'|\"[^\"]*\"|[A-Za-z_][\w .()/*+-]*?)\s*(:)(?=\s|$)",
                "captures": {
                    "2": {"name": "punctuation.definition.sequence.item.abinit"},
                    "3": {"name": name_scope, "patterns": [known_var]},
                    "4": {"name": "punctuation.separator.key-value.abinit"},
                },
            },
            "yaml-sequence": {
                "match": r"^\s*(-)(?=\s)",
                "captures": caps(**{"1": "punctuation.definition.sequence.item.abinit"}),
            },
            "yaml-flow-content": {"patterns": [
                {"include": "#yaml-comment"},
                {"include": "#quoted-string"},
                {"match": r"([A-Za-z_][\w|>]*)\s*(:)(?=\s)",
                 "captures": {
                     "1": {"name": name_scope, "patterns": [known_var]},
                     "2": {"name": "punctuation.separator.key-value.abinit"},
                 }},
                {"match": r"\b(?:null|true|false|yes|no)\b", "name": "constant.language.abinit"},
                {"match": r"[\[\]{}]", "name": "punctuation.definition.collection.abinit"},
                {"match": r",", "name": "punctuation.separator.abinit"},
                {"include": "#inline"},
            ]},
        },
    }


def write(name, grammar):
    path = ROOT / "syntaxes" / name
    path.write_text(json.dumps(grammar, indent=2, ensure_ascii=False) + "\n")
    print(f"wrote {path.relative_to(ROOT)} ({path.stat().st_size // 1024} KiB)")


if __name__ == "__main__":
    write("abinit.tmLanguage.json", input_grammar())
    write("abinit-output.tmLanguage.json", output_grammar())
