#!/usr/bin/env python3
"""Fetch the complete list of ABINIT input variables from the official sources.

Two independent sources are merged so that nothing is missed:

1. The documentation database (``abimkdocs/variables_<code>.py``) for abinit,
   anaddb, optic, multibinit, aim and atdep.  These files are parsed with
   ``ast`` -- nothing downloaded is ever executed.
2. The whitelists that the Fortran parsers actually accept
   (``chkvars`` in ``m_dtset.F90`` and ``anaddb_chkvars`` in
   ``m_anaddb_dataset.F90``).  These also provide the list of physical units.

The result is written to ``tools/abinit_variables.json``; run
``tools/build_grammars.py`` afterwards to regenerate the grammars.

Usage:
    python3 tools/fetch_variables.py [--ref master]
"""

import argparse
import ast
import datetime
import json
import re
import sys
import urllib.request
from pathlib import Path

RAW = "https://raw.githubusercontent.com/abinit/abinit/{ref}/{path}"
DOC_CODES = ["abinit", "anaddb", "optic", "multibinit", "aim", "atdep"]
OUT = Path(__file__).with_name("abinit_variables.json")


def fetch(ref, path):
    url = RAW.format(ref=ref, path=path)
    print(f"  fetching {url}", file=sys.stderr)
    with urllib.request.urlopen(url, timeout=60) as resp:
        return resp.read().decode("utf-8", errors="replace")


def parse_doc_variables(source):
    """Return [(name, vartype)] from an abimkdocs variables_*.py file."""
    result = []
    for node in ast.walk(ast.parse(source)):
        if not (isinstance(node, ast.Call) and getattr(node.func, "id", None) == "Variable"):
            continue
        kw = {k.arg: k.value for k in node.keywords}
        if "abivarname" not in kw:
            continue
        name = ast.literal_eval(kw["abivarname"]).split("@")[0]
        vartype = ast.literal_eval(kw["vartype"]) if "vartype" in kw else None
        result.append((name, vartype))
    return result


def parse_chkvars(source, routine):
    """Return (variables, units, logicals, strings) from a Fortran chkvars routine."""
    start = source.index(f"subroutine {routine}(")
    body = source[start:source.index("end subroutine", start)]
    lists = {"vars": [], "units": [], "ops": []}
    section = "vars"
    extra = {"list_logicals": [], "list_strings": [], "list_vars_img": []}
    for line in body.splitlines():
        s = line.strip()
        if s.startswith("!<ABINIT_UNITS>"):
            section = "units"
        elif s.startswith("!<ABINIT_OPERATORS>"):
            section = "ops"
        elif s.startswith("!</ABINIT_UNITS>") or s.startswith("!</ABINIT_OPERATORS>"):
            section = "vars"
        if s.startswith("!"):
            continue
        m = re.match(r"list_vars\s*=\s*(?:trim\(list_vars\)\s*//)?\s*'([^']*)'", s)
        if m:
            lists[section] += m.group(1).split()
            continue
        m = re.match(r"(list_logicals|list_strings|list_vars_img)\s*=\s*(?:trim\(\w+\)\s*//)?\s*'([^']*)'", s)
        if m:
            extra[m.group(1)] += m.group(2).split()
    return lists["vars"], lists["units"], extra["list_logicals"], extra["list_strings"]


def uniq(names):
    """Case-insensitive de-duplication keeping the first spelling, sorted."""
    seen = {}
    for n in names:
        seen.setdefault(n.lower(), n)
    return sorted(seen.values(), key=str.lower)


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--ref", default="master", help="git branch or tag of abinit/abinit (default: master)")
    args = ap.parse_args()

    by_code, string_vars = {}, []
    for code in DOC_CODES:
        entries = parse_doc_variables(fetch(args.ref, f"abimkdocs/variables_{code}.py"))
        by_code[code] = uniq(n for n, _ in entries)
        string_vars += [n for n, t in entries if t == "string"]

    abi_vars, units, logicals, strings = parse_chkvars(
        fetch(args.ref, "src/44_abitypes_defs/m_dtset.F90"), "chkvars")
    ana_vars, _, _, _ = parse_chkvars(
        fetch(args.ref, "src/77_ddb/m_anaddb_dataset.F90"), "anaddb_chkvars")
    # The anaddb whitelist also contains units and 'sqrt'; keep only variables.
    not_vars = {u.lower() for u in units} | {"sqrt", "end"}
    by_code["abinit_parser"] = uniq(abi_vars)
    by_code["anaddb_parser"] = uniq(v for v in ana_vars if v.lower() not in not_vars)

    all_vars = uniq(v for names in by_code.values() for v in names if v.lower() not in not_vars)
    data = {
        "_comment": "Generated by tools/fetch_variables.py -- do not edit by hand.",
        "source": f"https://github.com/abinit/abinit ({args.ref})",
        "fetched": datetime.date.today().isoformat(),
        "variables": all_vars,
        "string_variables": uniq(string_vars + strings),
        "logical_variables": uniq(logicals),
        "units": units,
        "by_code": by_code,
    }
    OUT.write_text(json.dumps(data, indent=1) + "\n")
    print(f"wrote {OUT}: {len(all_vars)} variables, {len(data['string_variables'])} string variables, "
          f"{len(units)} units", file=sys.stderr)


if __name__ == "__main__":
    main()
